# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: https://rtlee9.github.io
title: Paws Awhile
email: kjue69@gmail.com
author: Kelly Jue
description: >
  You can edit this line in _config.yml. It will appear in your document
  head meta (for Google search results) and in your feed.xml site
  description.
copyright: 'Copyright 2013. Paws Awhile Grooming. All Rights Reserved.'
credits:

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty
