# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: https://rtlee9.github.io
baseurl: /paws-awhile
title: Paws Awhile
email: kjue69@gmail.com
author: Kelly Jue
description: >
  You can edit this line in _config.yml. It will appear in your document
  head meta (for Google search results) and in your feed.xml site
  description.
copyright: 'Copyright 2013. Paws Awhile Grooming. All Rights Reserved.'
credits:

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: email
    fa: envelope
    url: mailto:ryantlee9@gmail.com
  - title: call
    fa: phone
    url:
  - title: twitter
    fa: twitter
    url:
  - title: instagram
    fa: instagram
    url:
