# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: https://paws-awhile-fresno.github.io
title: Paws Awhile
email: pawsawhilefresno@gmail.com
author: Kelly Jue
description: >
  Paws Awhile Fresno is a mobile grooming salon run by Kelly Jue. Paws Awhile serves the Fresno & Clovis area, and all neighboring cities.
copyright: 'Copyright 2013. Paws Awhile Grooming. All Rights Reserved.'
credits:

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
